# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "bigchaindb"
description = """
BigChainDB is a scalable blockchain database capable of up-to 1 million writes/second. How this fits in to the rest of the tooling ecosystem remains to be seen and is an ongoing discussion. 

The eris service will start your own BigChain node with default keys. Please build your own image (see location below for Dockerfile) to use fresh keys. 
"""

status = "alpha"

[service]
name = "bigchaindb"
image = "quay.io/eris/bigchaindb"
environment = [ "BIGCHAIN_DATABASE_HOST=rethinkdb" ]

command = "bigchaindb start"

[dependencies]
services = [ "rethinkdb" ]

[maintainer]
name = "Zach Ramsay"
email = "zach@erisindustries.com"

[location]
dockerfile =  "https://github.com/eris-ltd/common/blob/master/docker/bigchaindb/Dockerfile"
repository = "https://github.com/bigchaindb/bigchaindb"
website = "https://www.bigchaindb.com/"
