# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name           = "bitcoincore"
description  = """
The original implementation of Bitcoin. Its putative default functionality is constantly evolving. 

This eris service will connect to the bitcoin network.
"""

status = "ready"

[service]
image          = "quay.io/eris/bitcoincore"
data_container = true
ports          = [ "8333:8333", "8334:8334" ]
volumes        = [  ]
environment    = [  ]
restart = "always"

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/common/blob/master/docker/bitcoincore/Dockerfile"
repository = "https://github.com/bitcoin/bitcoin"
website = "https://bitcoincore.org/"

