# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name           = "eth"
description = """
An Ethereum full node. Please set appropriate environment variables.
"""

status = "alpha"

[service]
image          = "quay.io/eris/eth"
data_container = true
ports          = [ "8545:8545", "30303:30303" ]
volumes        = [  ]
environment    = [
  "ACCOUNT=0",
  "CHAIN_ID=ethereum",
  "LOG_LEVEL=2",
  "MAKEACCT=true",
  "PASSWORD=whatever"
]
restart = "always"

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/common/blob/master/docker/eth/Dockerfile"
repository = "https://github.com/ethereum/go-ethereum"
website = "https://www.ethereum.org/"

