# For more information on configurations, see the services specification:
# https://monax.io/docs/documentation/cli/latest/specifications/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "openbazaar"
description = """
A free Market for all. No Fees. No Restrictions.

The eris service runs an OpenBazaar Server.
"""

status = "beta"

[service]
name = "openbazaar"
image = "quay.io/eris/openbazaar-client:latest"
data_container = true
host_name = "ob"

[dependencies]
services = ["openbazaar-server"]

[maintainer]
name = "Monax Industries"
email = "support@monax.io"

[location]
dockerfile = "https://github.com/eris-ltd/eris-services/blob/master/docker/x86/openbazaar-client/Dockerfile"
repository = "https://github.com/OpenBazaar/OpenBazaar-Client"
website = "https://openbazaar.org/"

