# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "rethinkdb"
description = """
Dependency for BigChainDB
"""

status = "ready"

[service]
name = "rethinkdb"
image = "rethinkdb"
ports = [ "9999:8080", "28015"]
#volumes_from = [ "/data" ]
data_container = true
restart = "always"

[dependencies]

[maintainer]
name = "Zach Ramsay"
email = "zach@erisindustries.com"

[location]
dockerfile = "https://github.com/dockerfile/rethinkdb/blob/master/Dockerfile"
repository = "https://github.com/rethinkdb/rethinkdb"
website = "https://www.rethinkdb.com/"
