# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# NOTE: this definition file is a WIP
# and requires modification to work properly
# please see README/tutorial in repo

# both MINT_CHAINID and MINTX_PUBKEY
# need to be hardcoded. see test.sh
# in repo for more info

name = "toadserver"
description = """
A smart contract and IPFS Backed File Server. It is used internally as part of the `eris init` sequence.
"""

status = "alpha"

chain = "$chain:toad:l"

[service]
name = "toadserver"
image = "quay.io/eris/toadserver"
ports = [ "11113:11113" ]
volumes = [  ]
environment = [  
	"MINTX_NODE_ADDR=http://toad:46657/",
	"MINTX_CHAINID=$CHAIN_NAME", 
	"MINTX_SIGN_ADDR=http://keys:4767", 
	"MINTX_PUBKEY=$PUB_KEY",
	"ERIS_IPFS_HOST=http://ipfs",
	"TOADSERVER_IPFS_NODES=ip1,ip2,ip3"
]
restart = "always"

[dependencies]
services = [ "ipfs", "keys" ]

[maintainer]
name = "Zach Ramsay"
email = "zach@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/toadserver/blob/master/Dockerfile" 
repository = "https://github.com/eris-ltd/toadserver"
website = ""
