# Eris service definition for watchtower
# Start it with `$ eris services start watchtower`

# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the `$ docker run` command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "watchtower"
description = """
Automatically updates running Docker containers.

This eris service will watch your containers and update them whenever the base image is updated.
"""

status = "ready"

[service]
name = "watchtower"
image = "centurylink/watchtower"
data_container = false
volumes = [ "/var/run/docker.sock:/var/run/docker.sock" ]
restart = "always"

[dependencies]

[maintainer]
name = "Casey Kuhlman"
email = "casey@erisindustries.com"

[location]
dockerfile = "https://github.com/CenturyLinkLabs/watchtower/blob/master/Dockerfile"
repository = "https://github.com/CenturyLinkLabs/watchtower"
website = "https://labs.ctl.io/projects/watchtower/"
