# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "zcash"
description = """
Zcash is a decentralized and open source cryptocurrency that aims to set a new standard for privacy and anonymity through the use of groundbreaking cryptography.

The eris service will connect into the alpha testnet for zcash. Please first generate a new key and modify the bitcoin.conf file to your liking before running the node.
"""

status = "alpha"

[service]
name = "zcash"
image = "quay.io/eris/zcash"
data_container = true
command = "/var/zcash/src/zcashd -conf=/home/eris/.zcash/bitcoin.conf -datadir=/home/eris/.zcash -daemon"
ports = [ "8332", "8333:8333" ]
environment = [ "EXEC_HOST=zcash" ]
restart = "always"

[dependencies]

[maintainer]
name = "Casey Kuhlman"
email = "casey@erisindustries.com"

[location]
dockerfile = "https://github.com/eris-ltd/common/blob/master/docker/zcash/Dockerfile"
repository = "https://github.com/zcash/zcash"
website = "https://z.cash/"
